import APIService from '../services/services'; 
import Head from 'next/head';
import { useState } from 'react';
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/ReactToastify.css'
import Router from 'next/router';
import Link from 'next/link';

const apiService = new APIService('http://localhost:3001/api')

const Home = () => {
    const [ formData, setFormData ] = useState({
        username: "",
        password: ""
    });

    const handleSubmit = async (e: any) => {
        e.preventDefault();

        const response = await apiService.login(formData);

        if (response.success) {
            toast.success(response.message);

            setTimeout(() => {
                Router.push("/home");
            }, 1000);
        } else {
            toast.error(response.message);
        }
    };

    return (
        <>
        <Head>
            <title>X-books</title>
            <meta name='description' content='Generated by create next app'/>
            <meta name='viewport' content='width=device-width, initial-scale=1' />
            <link rel="stylesheet" href="" />
        </Head>
        <section>
            <div>
                <div>
                    <div>
                        <h1>
                            Log in!
                        </h1>
                        <form action="">
                            <div>
                                <label htmlFor="">
                                    Username
                                </label>
                                <input type="text" />
                            </div>
                            <div>
                                <label htmlFor="">
                                    Password
                                </label>
                                <input type="text" />
                            </div>
                            <button>
                                <p>
                                    Dont't have an account yet?
                                </p>
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </section>
        <ToastContainer/>
        </>
    )
}

export default Home;